package com.cloudcampus.intelligence.ai;

public enum AiFeature {
    ASSISTANT_QUERY,
    NOTICE_DRAFTING,
    HOMEWORK_DRAFTING,
    LESSON_PLAN_DRAFTING,
    QUIZ_DRAFTING,
    REPORT_EXPLANATION,
    REPORT_SUMMARY,
    STUDY_PLAN_DRAFTING,
    PARENT_PROGRESS_SUMMARY,
    FINANCE_SUMMARY,
    NOTICE_TRANSLATION,
    ADMISSION_ENQUIRY_ASSISTANT,
    SCHOOL_POLICY_QA
}
