package com.cloudcampus.intelligence.ai;

public enum AiRecommendationType {
    LESSON_PLAN_SUGGESTION,
    HOMEWORK_SUGGESTION,
    STUDENT_RISK_ACADEMIC,
    STUDENT_RISK_ATTENDANCE,
    STUDENT_RISK_DISCIPLINE,
    EXAM_PERFORMANCE_INSIGHT,
    PARENT_MESSAGE_DRAFT,
    FEE_REMINDER_SUGGESTION,
    ADMISSION_FOLLOW_UP,
    TIMETABLE_OPTIMIZATION,
    STAFF_WORKLOAD_INSIGHT,
    PLATFORM_HEALTH_INSIGHT,
    SUBSCRIPTION_RISK_INSIGHT
}
